services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: Random0027
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleet_user -d fleetdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://db:5433/fleetdb
      DB_USER: fleet_user
      DB_PASS: Random0027
      SECURITY_JWT_SECRET: 3f4428472b4b6250645367566b59703373367639792442264529482b4d625065
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./web-dashboard
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  dbdata: